spring.application.name=backend

# Configuración de base de datos PostgreSQL (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.scktblzlhnhkbmpqjaad
spring.datasource.password=SJRy9xJI8k6vKYnX
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Validate schema but don't drop/create since schema is already created
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port
server.port=8080

# JWT Secret Key (Debe ser de al menos 256 bits, aquí usamos una por defecto para dev)
jwt.secret=94a08da1fecbb6e8b46990538c7b50b294a08da1fecbb6e8b46990538c7b50b2
jwt.expiration=86400000
